- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo +nightly fmt
  language: system
  types: [rust]
  args: ["--", "--check"]
- id: clippy
  name: cargo lints clippy
  description: Lint rust sources
  entry: cargo lints clippy
  language: system
  args: ["--workspace", "--all-targets", "--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
